create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  role text not null default 'user' check (role in ('user', 'owner')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.entitlements (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  plan text not null default 'free' check (plan in ('free', 'premium', 'owner')),
  status text not null default 'inactive' check (status in ('inactive', 'active', 'cancelled', 'expired')),
  provider_customer_id text,
  provider_subscription_id text unique,
  current_period_end timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.daily_usage (
  user_id uuid not null references public.profiles(id) on delete cascade,
  usage_date date not null,
  words integer not null default 0 check (words >= 0),
  primary key (user_id, usage_date)
);

create table if not exists public.webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  event_name text not null,
  event_id text not null unique,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists entitlements_provider_customer_idx on public.entitlements(provider_customer_id);
create index if not exists daily_usage_date_idx on public.daily_usage(usage_date);

alter table public.profiles enable row level security;
alter table public.entitlements enable row level security;
alter table public.daily_usage enable row level security;
alter table public.webhook_events enable row level security;

drop policy if exists "users can read own profile" on public.profiles;
create policy "users can read own profile" on public.profiles for select using (auth.uid() = id);

drop policy if exists "users can read own entitlement" on public.entitlements;
create policy "users can read own entitlement" on public.entitlements for select using (auth.uid() = user_id);

drop policy if exists "users can read own usage" on public.daily_usage;
create policy "users can read own usage" on public.daily_usage for select using (auth.uid() = user_id);
